# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: mementor-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mementor
      POSTGRES_USER: mementor
      POSTGRES_PASSWORD: mementor2021
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    links:
      - db:mementor-db